[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.3.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.2.1" }
